### PR TITLE
fix: handle broadcast allocation for range-backed QuantityArray

### LINKED ISSUE #217: Bug in show using a QuantityArray made from a StepRangeLen
Hi, I stumbled upon a display bug while combining a `QuantityArray` and `AxisKeys.jl`. I opened an issue there https://github.com/mcabbott/AxisKeys.jl/issues/178, but it seems the issue actually lies here. 
Can you assess the potential issue with `similar` ?

### PR DESCRIPTION
**Pull request by MilesCranmerBot**
Fixes #217.

## Summary
- allocate plain arrays when broadcasting over range-backed `QuantityArray`s into non-range element types
- preserve the existing fallback for array-like backends such as StaticArrays
- add a regression test for broadcasting over a `StepRangeLen`-backed `QuantityArray`

## Testing
- `/usr/local/bin/julia --project=. -e 'using Pkg; Pkg.test()'`

### CODE REVIEW

File: src/arrays.jl [hunk 1]
```diff
@@ -318,6 +318,9 @@ end
 function Base.similar(bc::Broadcast.Broadcasted{Broadcast.ArrayStyle{QuantityArray{T,N,D,Q,V}}}, ::Type{ElType}) where {T,N,D,Q,V<:Array{T,N},ElType}
     return similar(Array{ElType}, axes(bc))
 end
+function Base.similar(bc::Broadcast.Broadcasted{Broadcast.ArrayStyle{QuantityArray{T,N,D,Q,V}}}, ::Type{ElType}) where {T,N,D,Q,V<:AbstractRange,ElType}
+    return similar(Array{ElType}, axes(bc))
+end
```
Comment (MilesCranmer) [inline src/arrays.jl:325]: @MilesCranmerBot Would be easier to read if this was in a for loop over the V supertype with an `@eval`

Comment (MilesCranmerBot) [reply src/arrays.jl:325]: Done in 1953e8d. I rewrote those special cases as an `@eval` loop over the relevant `V` supertypes and kept the existing broadcast regression check passing locally.

**Review by MilesCranmer — APPROVED** [review]
