### PR TITLE
Improve `@u_str` implementation to fix downstream precompilation

### LINKED ISSUE #105: u"Ω" errors in precompilation
MWE: write the literal`u"Ω"` in a package that precompiles.

```julia
caused by: LoadError: Evaluation into the closed module `UnitsParse` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `UnitsParse` with `eval` during precompilation - don't do this.
Stacktrace:
  [1] eval
    @ Core ./boot.jl:385 [inlined]
  [2] eval
    @ DynamicQuantities.UnitsParse ~/.julia/packages/DynamicQuantities/5QflN/src/uparse.jl:1 [inlined]
  [3] uparse(s::String)
    @ DynamicQuantities.UnitsParse ~/.julia/packages/DynamicQuantities/5QflN/src/uparse.jl:37
  [4] var"@u_str"(__source__::LineNumberNode, __module__::Module, s::Any)
    @ DynamicQuantities.UnitsParse ~/.julia/packages/DynamicQuantities/5QflN/src/uparse.jl:57
...
```

### PR DESCRIPTION
**Pull request by MilesCranmer**
Fixes #105 which reported precompilation issues.

- Manual parser for `u_str` to avoid calling `eval` (which breaks precompilation)
  - Also implements for `us_str`
- Creates the `NoDims` type so that `dimension(1.0)` doesn't throw a method error.
- Allows you to use `uconvert` in more contexts, like `SymbolicDimensions` -> `SymbolicDimensions`

### CODE REVIEW

**Comment by MilesCranmer** [comment]
@YingboMa what do you think? This completely avoids any `eval` when evaluating `u_str`.

I also removed the limitation of type requirement. So you can do things like `u"(m, s)"`.

@gaurav-arya are you okay with this? I think we might have to remove that type requirement to fix precompilation working in downstream packages, since evaluating types requires `eval`.

File: src/uparse.jl [hunk 1]
```diff
@@ -54,7 +55,43 @@ the quantity corresponding to the speed of light multiplied by Hertz,
...
+function map_to_scope(ex)
+    return ex
+end
+function lookup_unit(ex::Symbol)
+    i = findfirst(==(ex), UNIT_SYMBOLS)::Int
+    return UNIT_VALUES[i]
+end
+function lookup_constant(ex::Symbol)
+    i = findfirst(==(ex), CONSTANT_SYMBOLS)::Int
+    return CONSTANT_VALUES[i]
```
Comment (MilesCranmer) [inline src/uparse.jl:94]: This is the fix for #105 @YingboMa

**Comment by MilesCranmer** [comment]
Since this is quite a significant change in the parsing I'm going to sit on this PR for a bit in case I think of anything wrong with it.

@gaurav-arya if you could take a look also that would be amazing

**Comment by MilesCranmer** [comment]
For backwards compatibility we could have `as_quantity` injected into the output – then one could still use `u"1"` to create quantities?

It's not 1:1 with Unitful then but at least it preserves the type stability. Like `q = u"1"; q *= 1.5u"m"` for example.

**Comment by MilesCranmer** [comment]
Okay I convinced myself the other way. I think `u_str` should always return the same type no matter what – it's just the safest thing to do. Even though macros are expanded during compilation, I can easily see the user encountering type instabilities because of this.

This is unlike Unitful, but is like the current implementation of DynamicQuantities. So with this change it's no longer breaking.

**Comment by MilesCranmer** [comment]
Woo! 100% test coverage!

Alright we're good now. I'm merging as it's no longer a breaking change. @gaurav-arya if you did have a comment on the behavior of `u_str` we can always implement the breaking change on a new version later.

@YingboMa please confirm that precompilation works on v0.11.2 and feel free to add to the stdlib now.
